# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100, null=True, verbose_name='Número de identificacion')),
                ('direction', models.CharField(max_length=300, null=True, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Teléfono Fijo')),
                ('cellphone', models.CharField(max_length=80, null=True, verbose_name='Número de celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
